title: Calliope Dokumentation
email: info@calliope.cc
description: Technische Dokumentation des Calliope mini CO2 Sensors.
twitter_username: CalliopeMini
github_username:  calliope-edu
markdown: kramdown
theme: jekyll-theme-slate